package model;
// Generated 16-oct-2017 10:49:08 by Hibernate Tools 4.3.1



/**
 * Automovil generated by hbm2java
 */
public class Automovil  implements java.io.Serializable {


     private Integer id;
     private String marca;
     private int modelo;
     private int placa;

    public Automovil() {
    }

    public Automovil(String marca, int modelo, int placa) {
       this.marca = marca;
       this.modelo = modelo;
       this.placa = placa;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public int getModelo() {
        return this.modelo;
    }
    
    public void setModelo(int modelo) {
        this.modelo = modelo;
    }
    public int getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(int placa) {
        this.placa = placa;
    }




}


